resources:
  - name: tester.git
    type: git
    source:
      uri: git@github.com:ansel1/tester.git
      branch: master

  - name: tester-docker-image
    type: docker-image
    source:
      repository: ansel1/tester
      username: ansel1
      password: 67ltpGD7LWZzGVg

jobs:
- name: build-tester-docker-image
  plan:
    - get: tester.git
    - put: tester-docker-image
      params: {build: tester.git}